### ISSUE TITLE
Item rendering performance issue

### ISSUE THREAD

**Issue by raoulvdberge** [bdew/covers#6]
Hi,

When rendering a lot of covers at once (for example in JEI) FPS drops from 40 fps to 3 fps on my machine.

Without JEI with @covers open:
![Without JEI](http://i.imgur.com/RoB5vC6.png)

With JEI with @covers open:
![With JEI](http://i.imgur.com/M0DNsX4.png)

If I only display vanilla items (or other mod items) in JEI, FPS goes back to normal.
- Forge 2011 (I do know my Forge version is outdated, but that is most likely irrelevant to the issue?)
- covers-0.3.0.6-mc1.10.2
- jei_1.10.2-3.7.11.238

Thanks!

**Comment by bdew** [comment]
This is a known issue. Covers take some complicated steps to transform the textures of the original blocks and apply it to the cover model. When they are placed in world it's less of an issue due to caching - but there is none for items and it gets even worse when there are many different covers displayed at once (as in JEI).

I have a few changes planned that will improve performance in the future.

For now as a workaround you can reduce the number of covers shown in JEI by changing JEI Display Mode to  "MINIMAL" in the config or remove them entirely from JEI by setting it to "NONE".

**Comment by rigerc** [comment]
Setting the option to NONE doesn't seem to work for me. Is it broken?

**Comment by bdew** [comment]
This should be significantly improved in newer builds with the new cache.
